language: generic
os: osx
osx_image: xcode9.4

install: sudo pip install tox setuptools wheel twine

script: tox -epy27
deploy:
  provider: pypi
  user: yelplabs
  distributions: sdist bdist_wheel
  skip_existing: true
  password:
    secure: I0m1KUbsEBmPtQ/CQGmPDHr8FUx96IU9s6IM/HqmF/lRTvIp/uPAVxRSNjxvOvVecCLRBDP6H60wSTIb1wVXME7Zg1PHhioOUb1gzWJ7Atq4QTdf5+qJfdZs+fvOoKuWYukj2pWpY5HypIq9crM7L5VzeOYAuYwnK65tJK9yvfo=
  on:
    tags: true
    repo: Yelp/osxcollector
    branch: master
